# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Women In Tech
email: alex.ho.1990@live.co.uk
description: > # this means to ignore newlines until "baseurl:"
  We aim to empower and give a voice to women on the global technology platform
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: alexhobag1
github_username:  jekyll

# Build settings
markdown: kramdown
include: ['_pages']
sass:
    style: compressed

